import { POStatus, VendorRating, WeeklyData } from './types';

export const CURRENT_WEEK_DATA: WeeklyData = {
  weekStarting: 'Oct 23, 2023',
  totalPOsRaised: 34,
  totalPOValue: 12500000,
  pendingIndentsCount: 12,
  pendingIndentsValue: 450000,
  pendingApprovals: 5,
  deliveriesCompleted: 28,
  deliveriesDelayed: 6,
  qualityIssuesReported: 2,
  topMaterials: [
    { name: 'Reinforcement Steel (TMT)', value: 5500000 },
    { name: 'Grade 53 Cement', value: 3200000 },
    { name: 'RMC (M30/M40)', value: 1800000 },
    { name: 'Red Bricks', value: 900000 },
    { name: 'Electrical Conduits', value: 400000 },
  ],
  projects: [
    {
      id: 'P001',
      name: 'WABAG',
      budgetUtilization: 82,
      materialRequirementsReceived: 15,
      posRaisedCount: 12,
      deliveriesCompleted: 10,
      outstandingItems: 5,
      criticalShortages: ['20mm TMT Bars', 'Waterproofing Compound'],
    },
    {
      id: 'P002',
      name: 'SRM AP',
      budgetUtilization: 65,
      materialRequirementsReceived: 22,
      posRaisedCount: 18,
      deliveriesCompleted: 15,
      outstandingItems: 7,
      criticalShortages: [],
    },
    {
      id: 'P003',
      name: 'Blue Star',
      budgetUtilization: 91,
      materialRequirementsReceived: 8,
      posRaisedCount: 4,
      deliveriesCompleted: 3,
      outstandingItems: 9,
      criticalShortages: ['Copper Piping', 'Insulation Material'],
    },
  ],
  highValuePOs: [
    {
      poNumber: 'PO-23-1098',
      vendorId: 'V01',
      vendorName: 'Tata Steel Ltd',
      projectId: 'P001',
      projectName: 'WABAG',
      materialName: '500MT TMT Rebars',
      value: 3500000,
      dateRaised: '2023-10-24',
      deliveryDueDate: '2023-10-30',
      status: POStatus.APPROVED,
    },
    {
      poNumber: 'PO-23-1102',
      vendorId: 'V02',
      vendorName: 'Ultratech Cement',
      projectId: 'P002',
      projectName: 'SRM AP',
      materialName: '1000 Bags Cement',
      value: 1200000,
      dateRaised: '2023-10-25',
      deliveryDueDate: '2023-10-29',
      status: POStatus.DELAYED,
    },
    {
      poNumber: 'PO-23-1105',
      vendorId: 'V05',
      vendorName: 'Larsen & Toubro (Supply)',
      projectId: 'P003',
      projectName: 'Blue Star',
      materialName: 'HVAC Units',
      value: 2800000,
      dateRaised: '2023-10-26',
      deliveryDueDate: '2023-11-05',
      status: POStatus.PENDING,
    },
  ],
  vendors: [
    {
      id: 'V01',
      name: 'Tata Steel Ltd',
      rating: VendorRating.HIGH,
      onTimeDeliveryScore: 95,
      avgLeadTime: 5,
    },
    {
      id: 'V02',
      name: 'Ultratech Cement',
      rating: VendorRating.MEDIUM,
      onTimeDeliveryScore: 82,
      avgLeadTime: 3,
    },
    {
      id: 'V03',
      name: 'Local Aggregates Co.',
      rating: VendorRating.LOW,
      onTimeDeliveryScore: 65,
      avgLeadTime: 2,
    },
  ],
};